services:
  - type: web
    name: mesh-tech-session
    runtime: node
    plan: free
    repo: https://github.com/mesh057/MESH-TECH-SESSION
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
    ports:
      - port: 8000
        protocol: http
